# SITE CONFIGURATION
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.maartenpaauw.com/" # the base hostname & protocol for your site

# THEME-SPECIFIC CONFIGURATION
theme_settings:
  # Meta
  title: "'s blog"
  title_tag: "Maarten's blog"
  gravatar: "c32c1a3574c36662aee8a65da32ca8ee"
  description: "Maarten Paauw's Blog" # used by search engines

  # Header and footer text
  header_text: >
     <h3>Hello, I'm Maarten.</h3>
  header_text_feature_image:
  footer_text: >
    written with <i class="fa fa-heart orange" aria-hidden="true"></i> by Maarten
#   Aangedreven door <a href="http://jekyllrb.com">Jekyll</a><br/>
#   met <a href="https://rohanchandra.github.io/project/type/">Type Theme</a> als thema.

  # Icons
  rss: false
  email_address: "maartenpaauw@gmail.com"
  behance:
  bitbucket: "m44rt3np44uw"
  dribbble:
  facebook:
  flickr:
  github: "maartenpaauw"
  google_plus:
  instagram:
  linkedin: "https://www.linkedin.com/in/paauw"
  pinterest:
  reddit:
  soundcloud:
  stack_exchange: "http://stackexchange.com/users/1794576/maartenpaauw"
  steam:
  tumblr:
  twitter:
  wordpress:
  youtube:

  # Scripts
  google_analytics: "UA-40230993-7"
  disqus_shortname: "maartenpaauw"
  muut_community_name: # From muut.com settings, e.g. "muttcommunityname"
  katex: true # Enable if using math markup

  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next: "Next"
  str_prev: "Previous"
  str_continue_reading: "Continue reading"

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Source+Sans+Pro:400,700,700italic,400italic"

  # Post navigation
  post_navigation: true

# PAGINATION
paginate: 5
paginate_path: "blog/page:num"

# BUILD SETTINGS
markdown: "kramdown"
highlighter: "rouge"
sass:
  sass_dir: "_sass"
  style: ":compressed"
gems: [jekyll-paginate, jekyll-sitemap]
