# SITE CONFIGURATION
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://m44rt3np44uw.github.io/" # the base hostname & protocol for your site

# THEME-SPECIFIC CONFIGURATION
theme:
  # Meta
  title: Maarten's blog
  gravatar: c32c1a3574c36662aee8a65da32ca8ee
  description: "Blog van Maarten Paauw" # used by search engines

  # Header and footer text
  header_text: >
     <h3>Hallo, ik ben Maarten.</h3>
  header_text_feature_image:
#  header_text_feature_image: img/2016-06-27-test.jpg
  footer_text: >
   Aangedreven door <a href="http://jekyllrb.com">Jekyll</a> met <a href="https://rohanchandra.github.io/project/type/">Type Theme</a>

  # Icons
  rss: false
  email_address: maartenpaauw@gmail.com # Full email address, e.g. "sam@example.com"
  behance:
  bitbucket: m44rt3np44uw
  dribbble:
  facebook:
  flickr:
  github: m44rt3np44uw
  google_plus:
  instagram:
  linkedin: https://nl.linkedin.com/in/m44rt3np44uw # Full URL
  pinterest:
  reddit:
  soundcloud:
  stack_exchange: http://stackexchange.com/users/1794576/m44rt3np44uw # Full URL
  steam:
  tumblr:
  twitter:
  wordpress:
  youtube:

  # Scripts
  google_analytics: UA-40230993-7 # Tracking ID, e.g. "UA-000000-01"
  disqus_shortname: maartenpaauw
  katex: true # Enable if using math markup

  # Localization strings
  str_follow_on: "Volg me op"
  str_rss_follow: "Volg mijn RSS feed"
  str_email: "E-mail"
  str_next: "Volgende"
  str_prev: "Vorige"
  str_continue_reading: "Lees meer"

  # Colours, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"
  google_fonts: "Source+Sans+Pro:400,700,700italic,400italic"

  # Post navigation
  post_navigation: true

# PAGINATION
paginate: 5
paginate_path: "blog/page:num"

# BUILD SETTINGS
markdown: kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: :compressed
gems: [jekyll-paginate]
